Repository KendallDoesCoding/portfolio, pull requests merged in 2023-03, with the labels that each got.

#30 made changes with height and projectCard
  index.html
  styles.css
Labels: size/M

#31 Redesigned and added New Logo
  images/newlogo.png
  images/newlogo.svg.svg
  index.html
  styles.css
Labels: size/S

#32 chore: don't allow user to select text on website
  styles.css
Labels: size/XS

#33 fix: hyperlink not working on contact in navbar
  index.html
Labels: size/XS

#35 <Fixed Navbar> Modified alignment and font size
  styles.css
Labels: size/XS
